### PR TITLE
Switch to Apache licenced curve25519. Remove some calls to system.out.println()

### PR DESCRIPTION
**Pull request by tmyroadctfig**
Thanks for your excellent library.

I switched the curve25519 implementation away from the WhisperSystems one because that is licenced under the GPL. The zeromq one is Apache licenced.

Also just changed some logging to remove some chatty log messages, and messages going to System.out.println().

### CODE REVIEW

**Comment by horrorho** [comment]
@tmyroadctfig Thank you!

I've quickly eyeballed the changes and they appear sound, however I would like to examine them in more detail and test them. Hopefully I can get this done over the next few days or at the latest by the weekend.

**Comment by horrorho** [comment]
Ok! I've pulled in the changes with the exception of the system out calls in the [FileAssembler](https://github.com/horrorho/InflatableDonkey/blob/b1f0e3f2692ad164a16433e9efa9a65ad49bb6a4/src/main/java/com/github/horrorho/inflatabledonkey/file/FileAssembler.java), although I have modified the existing logging levels.

The file output information is a throwback to [iLoot](https://github.com/hackappcom/iloot). I can understand why it may appear as visual clutter but it does indicate the files that are being retrieved and the rate at which they are being retrieved. It gives the user an indication that _something_ is happening which may not be the case with poor connection.

I've made the assumption that the casual user will not tinker with log settings.

I've also removed the .idea folder.

Thank you for your contribution.

**Comment by tmyroadctfig** [comment]
Thanks for merging in the changes. 

I'm using your code as a library in my application, so I want to avoid the System.out calls. Would it be OK if wrapped those calls with a check on a system property so that I can disable them? If that sounds OK I'll create a new pull request with those changes.

**Comment by horrorho** [comment]
I'll add in a `--quiet` switch or similar if that's acceptable. It's probably easier for me to get it done, as the command line parsing is somewhat tortuous. I'll get it done tomorrow evening after work.

**Comment by tmyroadctfig** [comment]
That sounds perfect. It's greatly appreciated.

Thanks, Luke

**Comment by horrorho** [comment]
Done.

**Pull request merged**
